const places = [
    "MURADİYE CAMİİ",
    "HAMZABEY CAMİİ",
    "ULU CAMİ",
    "BALİBEY HAN",
    "PİRİNÇ HAN",
    "EMİR HAN",
    "FİDAN HAN",
    "GEYVE HAN",
    "ORHAN BEY CAMİİ",
    "YEŞİL TÜRBE",
    "EMİRSULTAN CAMİİ",
    "EMİRSULTAN HAMAMI",
    "EMİRSULTAN TÜRBESİ",
    "YEŞİL HAMAMI",
    "HAMZABEY TÜRBESİ",
    "ORHANGAZİ TÜRBESİ",
    "APOLYONT HAN",
    "TUZ HAN",
    "KÜTAHYA HAN",
    "TAHIL HAN",
    "IRGANDI KÖPRÜSÜ",
    "1.MURAT CAMİİ",
    "YENİ KAPLICA",
    "YILDIRIM BEYAZIT CAMİİ",
    "YILDIRIM BEYAZIT TÜRBESİ",
    "ÜFTADE CAMİİ VE TÜRBESİ",
    "ESKİ KAPLICA",
    "KAPAN HAN",
    "MAHKEME HAMAMI",
    "HARAÇÇIOĞLU MEDRESESİ",
    "ÜÇ KUZULAR CAMİİ",
    "ÜÇ KUZULAR TÜRBESİ",
    "ESKİŞEHİR HANI",
    "KUBBELİ HAN",
    "BEDESTEN",
    "BAKIRCILAR ÇARŞISI",
    "ÜFTADE TEKKE CAMİİ",
    "YILDIRIM MEDRESESİ",
    "SARAYLILAR TÜRBESİ",
    "ŞEHZADE AHMET TÜRBESİ",
    "GÜLŞAH HATUN TÜRBESİ",
    "MÜKRİME HATUN TÜRBESİ",
    "CEM SULTAN TÜRBESİ",
    "GÜLRUH HATUN TÜRBESİ",
    "MOLLA FENARİ CAMİİ",
    "MOLLA FENARİ TÜRBESİ",
    "SOMUNCU BABA TÜRBESİ",
    "TEZ VEREN TÜRBESİ",
    "HÜSNÜ GÜZEL HAMAMI",
    "İSMAİL HAKKI BURSEVİ CAMİİ VE TÜRBESİ",
    "TARİHİ BELEDİYE BİNASI",
    "TOPHANE SURLARI",
    "SÜLEYMAN ÇELEBİ TÜRBESİ",
    "ESKİ İPEK HAN",
    "OSMANGAZİ TÜRBESİ",
    "GÖKDERE MEDRESESİ",
    "GELİNCİK ÇARŞISI",
    "2.MURAT TÜRBESİ",
    "YILDIRIM HAMAMI",
    "NASUH PAŞA HAMAMI",
    "KEÇELİ HAMAMI",
    "YOĞURT HAN",
    "YORGANCILAR ÇARŞISI",
    "HÜMA HATUN TÜRBESİ",
    "ŞEHZADE MAHMUT TÜRBESİ",
    "KOZA HAN",
    "YEŞİL CAMİİ",
    "OKÇU BABA TÜRBESİ",
    "KARAMUSTAFA KAPLICASI",
    "MURADİYE TÜRBELERİ",
    "KAPALIÇARŞI",
    "ŞEHZADE MUSTAFA TÜRBESİ",
    "DEMİRTAŞ HAMAMI",
    "1.MURAT TÜRBESİ",
    "MURADİYE MEDRESESİ",
    "ÇELİK PALAS HAMAMI",
    "GÜLBAHAR HATUN TÜRBESİ",
    "ŞİRİN HATUN TÜRBESİ"
  ]
  ;
  
  export default places;
  